import{a as p,n as a,S as y}from"./assets/vendor-9c3cb3f5.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const h="https://pixabay.com/api/",g="42103820-367af78541649bbd92098b568";class m{constructor(){this.searchQuery="",this.page=1}async getImage(){try{const e=await p.get(h,{params:{key:g,q:this.searchQuery,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:40,page:this.page}});return this.page+=1,e.data}catch(e){throw console.error("Error fetching images:",e),e}}resetPage(){this.page=1}get query(){return this.searchQuery}set query(e){this.searchQuery=e}}const i=new m,b=document.querySelector("form#search-form"),d=document.querySelector("div.gallery"),n=document.querySelector("button.load-more");let l=1;b.addEventListener("submit",L);n.addEventListener("click",v);n.classList.add("is-hidden");async function L(o){if(o.preventDefault(),d.innerHTML="",i.query=o.currentTarget.elements.searchQuery.value.trim(),i.resetPage(),i.query===""){a.Notify.info("Please enter your search query!");return}try{const{data:e}=await i.getImage(l);let r=e.hits;r.length===0?a.Notify.failure("Sorry, there are no images matching your search query. Please try again."):(f(r),n.classList.remove("is-hidden"),a.Notify.success(`Hooray! We found ${e.totalHits} images.`))}catch(e){a.Notify.info("We're sorry, but you've reached the end of search results."),console.log(e)}}async function v(){l++;try{const{data:o}=await i.getImage(l);let e=o.hits;f(e),e.length<15&&(n.classList.add("is-hidden"),a.Notify.info("We're sorry, but you've reached the end of search results."))}catch(o){console.log(o)}}function f(o){const e=o.map(r=>`<a href="${r.largeImageURL}" class="photo-card" data-lightbox="gallery">
        <div class="thumb"><img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" /></div>
        <div class="info">
          <p class="info-item"><b>Likes</b><span>${r.likes}</span></p>
          <p class="info-item"><b>Views</b><span>${r.views}</span></p>
          <p class="info-item"><b>Comments</b><span>${r.comments}</span></p>
          <p class="info-item"><b>Downloads</b><span>${r.downloads}</span></p>
        </div>
      </a>`).join("");d.insertAdjacentHTML("beforeend",e),new y(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250})}
//# sourceMappingURL=commonHelpers.js.map
