import{a as f,n as a,S as p}from"./assets/vendor-61e865f2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const h="https://pixabay.com/api/",y="42103820-367af78541649bbd92098b568";class g{constructor(){this.searchQuery="",this.page=1}async getImage(){try{const e=await f.get(h,{params:{key:y,q:this.searchQuery,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:40,page:this.page}});return this.page+=1,e.data}catch(e){throw console.error("Error fetching images:",e),e}}resetPage(){this.page=1}get query(){return this.searchQuery}set query(e){this.searchQuery=e}}const i=new g,m=document.querySelector("form#search-form"),d=document.querySelector("div.gallery"),n=document.querySelector("button.load-more");m.addEventListener("submit",b);n.addEventListener("click",L);n.classList.add("is-hidden");function b(o){if(o.preventDefault(),d.innerHTML="",i.query=o.currentTarget.elements.searchQuery.value.trim(),i.resetPage(),i.query===""){a.Notify.info("Please enter your search query!");return}else i.getImage().then(e=>{let r=e.hits;r.length===0?a.Notify.failure("Sorry, there are no images matching your search query. Please try again."):r.length<40?(l(r),n.classList.remove("is-hidden"),a.Notify.success(`Hooray! We found ${e.totalHits} images.`)):(l(r),n.classList.remove("is-hidden"),a.Notify.success(`Hooray! We found ${e.totalHits} images.`))}).catch(e=>{a.Notify.info("We're sorry, but you've reached the end of search results."),console.log(e)})}function L(){i.getImage().then(o=>{let e=o.hits;l(e),e.length<40&&(n.classList.add("is-hidden"),a.Notify.info("We're sorry, but you've reached the end of search results."))})}function l(o){const e=o.map(r=>`<a href="${r.largeImageURL}" class="photo-card" data-lightbox="gallery">
        <div class="thumb"><img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" /></div>
        <div class="info">
          <p class="info-item"><b>Likes</b><span>${r.likes}</span></p>
          <p class="info-item"><b>Views</b><span>${r.views}</span></p>
          <p class="info-item"><b>Comments</b><span>${r.comments}</span></p>
          <p class="info-item"><b>Downloads</b><span>${r.downloads}</span></p>
        </div>
      </a>`).join("");d.insertAdjacentHTML("beforeend",e),new p(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250})}
//# sourceMappingURL=commonHelpers.js.map
